# MongoDB
mongodb_uri: "mongodb://localhost:27017"
mongodb_db: "lw_logger"

# PostgresDB
postgres_url: "postgresql://:@ep-billowing-cake-07027396.eu-central-1.aws.neon.tech/neondb?sslmode=require"

# Databases, some features require a specific database while some will allow a choice. No idea how this will be implemented yet
postgres: true
mongodb: true

# true: feature on, false: feature off
logging: true
feature_flags: true
auth: true

# Auth
secret_key: "watermelonisthabest"
## Jwt settings
jwt-iss: "my-issuer"

#Routes
logging_route: "log"
feature_flags_route: "featureflags"
